SELECT ENAME
FROM BANK.EMP
WHERE DEPTNO = 20;

SELECT *
FROM BANK.EMP
WHERE JOB IN('MANAGER','KING','CLERK');

SELECT *
FROM BANK.EMP
WHERE COMM IS NULL;

SELECT EMPNO,ENAME,SAL,DEPTNO 
FROM BANK.EMP
WHERE DEPTNO = 10
UNION
SELECT EMPNO,ENAME,SAL,DEPTNO 
FROM BANK.EMP
WHERE DEPTNO = 20;

SELECT EMPNO,ENAME,SAL,DEPTNO 
FROM BANK.EMP
WHERE LENGTH(ENAME) >= 5;

SELECT NEXT_DAY(sysdate,'월요일')
FROM DUAL;

SELECT SUBSTR(JOB,-LENGTH(JOB),2) 
FROM BANK.EMP

SELECT TRIM('_ _ORACLE_ _') AS TRIM
,TRIM(LEADING FROM'_ _ORACLE_ _') AS TRIM_LEADING
FROM DUAL;

SELECT NEXT_DAY(sysdate,'월요일'),LAST_DAY(SYSDATE) 
FROM DUAL;

SELECT Extract(YEAR FROM hiredate),Extract(month FROM hiredate),Extract(day FROM hiredate)
FROM BANK.EMP;

SELECT round(sysdate,'yyyy') ,round(sysdate,'q')
FROM DUAL;

SELECT SYSDATE 
,to_char(sysdate,'mm')
,to_char(sysdate,'mon')
FROM DUAL;

SELECT nvl2(comm,'O','X'),job,DECODE(job,'MANAGER',sal*0.2,'SALESMAN',sal*0.1,'CLERK',SAL*0.05) AS 보나스
FROM BANK.EMP;

SELECT SUM(COMM) FROM BANK.EMP
SELECT nvl(COMM,0), SAL+COMM ,SAL+NVL(COMM,0) FROM BANK.EMP;


SELECT COUNT(*)
FROM BANK.EMP,BANK.DEPT

SELECT EMPNO,ENAME,D.DEPTNO
FROM BANK.EMP E,BANK.DEPT D
WHERE E.DEPTNO = D.DEPTNO

SELECT *
FROM BANK.EMP E JOIN BANK.DEPT D ON (E.DEPTNO = D.DEPTNO)

SELECT *
FROM BANK.EMP E JOIN BANK.DEPT D USING (DEPTNO)

SELECT *
FROM BANK.EMP E,BANK.SALGRADE S 
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL

SELECT E1.EMPNO,E1.ENAME,E1.MGR,
	   E2.EMPNO AS MGR_NO,E2.ENAME AS MGR_NAME
FROM BANK.EMP E1, BANK.EMP E2
WHERE E1.MGR=E2.EMPNO



