SELECT ENAME
FROM BANK.EMP
WHERE DEPTNO = 20;

SELECT *
FROM BANK.EMP
WHERE JOB IN('MANAGER','KING','CLERK');

SELECT *
FROM BANK.EMP
WHERE COMM IS NULL;

SELECT EMPNO,ENAME,SAL,DEPTNO 
FROM BANK.EMP
WHERE DEPTNO = 10
UNION
SELECT EMPNO,ENAME,SAL,DEPTNO 
FROM BANK.EMP
WHERE DEPTNO = 20;

SELECT EMPNO,ENAME,SAL,DEPTNO 
FROM BANK.EMP
WHERE LENGTH(ENAME) >= 5;

SELECT NEXT_DAY(sysdate,'월요일')
FROM DUAL;

SELECT SUBSTR(JOB,-LENGTH(JOB),2) 
FROM BANK.EMP

SELECT TRIM('_ _ORACLE_ _') AS TRIM
,TRIM(LEADING FROM'_ _ORACLE_ _') AS TRIM_LEADING
FROM DUAL;

SELECT NEXT_DAY(sysdate,'월요일'),LAST_DAY(SYSDATE) 
FROM DUAL;

SELECT Extract(YEAR FROM hiredate),Extract(month FROM hiredate),Extract(day FROM hiredate)
FROM BANK.EMP;

SELECT round(sysdate,'yyyy') ,round(sysdate,'q')
FROM DUAL;
